### ISSUE TITLE
if else doesn't work

### ISSUE THREAD

**Issue by rajeshisnepali** [appleboy/ssh-action#255]
```======CMD======
echo "Deploying scripts"
cd /var/www/sites
if [[ $(git rev-parse --abbrev-ref HEAD) != "dev" ]] then echo "changing branch" else echo "same branch" fi
ls
pwd
whoami

======END======
err: zsh:6: parse error near `whoami'
```

if else doesn't work

**Comment by dingram** [comment]
This isn't a problem with this action, but with your script. Specifically, it's not possible to have `if` statements all on one line without using semi-colons.

Replacing it with either of the following should work:

```
# One-liner, with semicolons after each command:
if [[ $(git rev-parse --abbrev-ref HEAD) != "dev" ]]; then echo "changing branch"; else echo "same branch"; fi
```

```
# Longer version that doesn't need semicolons:
if [[ $(git rev-parse --abbrev-ref HEAD) != "dev" ]]; then
  echo "changing branch"
else
  echo "same branch"
fi
```

This is because the shell (`zsh` in this case) keeps treating everything after the first `echo` as parameters for that command, until it reaches the end of the line or a semicolon. Although most shells need the semicolon before `then`, it's optional in `zsh if you're using `[[` and `]]` in the condition... but I'd still recommend it.

**Comment by appleboy** [comment]
Put your script into a single file. Maybe it should resolve your problem.
