### ISSUE TITLE
npm and pm2 command not working

### ISSUE THREAD

**Issue by cakasuma** [appleboy/ssh-action#44]
i cant use npm install or pm2 in the script, is there any way to do this

**Comment by insign** [comment]
I can use normally. Verify if the $PATH was loaded. Try `source ~/.profile`

**Comment by appleboy** [comment]
See https://github.com/appleboy/ssh-action/issues/21

**Comment by fcbuz2000** [comment]
npm: command not found
Reason:
I use nvm for the server node environment, and nvm will not install the node environment in the /usr/local/bin/ directory, so that sudo can't find the corresponding instructions, and finally create a soft connection to solve

sudo ln -s "$NVM_DIR/versions/node/$(nvm version)/bin/node" "/usr/local/bin/node"
sudo ln -s "$NVM_DIR/versions/node/$(nvm version)/bin/npm" "/usr/local/bin/npm"
sudo ln -s "$NVM_DIR/versions/node/$(nvm version)/bin/pm2" "/usr/local/bin/pm2"

you can test "sudo npm -v"

https://blog.csdn.net/weixin_40599109/article/details/110825357

**Comment by gulshanAI** [comment]
Find where is your node, npm, and pm2

`whereis node`
**For Me Output**
`node: /home/abhimanyu/.nvm/versions/node/v18.12.1/bin/node`
**after that link it via**
`sudo ln -s "$NVM_DIR/versions/node/v18.12.1/bin/pm2" "/usr/local/bin/pm2"`

`whereis npm`
**For Me Output**
`npm: /home/abhimanyu/.nvm/versions/node/v18.12.1/bin/npm`
**after that link it via**
`sudo ln -s "$NVM_DIR/versions/node/v18.12.1/bin/node" "/usr/local/bin/node"`

`whereis pm2`
**For Me Output**
`pm2: /home/abhimanyu/.nvm/versions/node/v18.12.1/bin/pm2`
**after that link it via**
`sudo ln -s "$NVM_DIR/versions/node/v18.12.1/bin/npm" "/usr/local/bin/npm"`

**Here my path is mention your path me be diffrent**

This will resolved the issue
